import '../sass/main.sass';
import newAccordion from './includes/newAccordion.js';
import sidebar from './includes/sidebar.js';
import isDropdown from './includes/isDropdown.js';
import closeAlert from './includes/closeAlert.js';
import profileFormValidation from './includes/profileFormValidation.js';
import searchFormValidation from './includes/searchFormValidation.js';
import bookmarkFormValidation from './includes/bookmarkFormValidation.js';
import fileFormValidation from './includes/fileFormValidation.js';
import createFormValidation from './includes/createFormValidation.js';
import modalSearchFormValidation from './includes/modalSearchFormValidation.js';
import accordion from './includes/accordion.js';
import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import scrollToId from './includes/scrollToId.js';
import modal from './includes/modal.js';
import loadMore from './includes/loadMore.js';
import select from './includes/select.js';
import loginFormValidation from './includes/loginFormValidation.js';
import tariffsSlider from './includes/tariffsSlider.js';
import reviewsSlider from './includes/reviewsSlider.js';
import feedbackFormValidation from './includes/feedbackFormValidation.js';
import registrationFormValidation from './includes/registrationFormValidation.js';
import phoneMask from './includes/phoneMask.js';
import forgotFormValidation from './includes/forgotFormValidation.js';
import passwordFormValidation from './includes/passwordFormValidation.js';
import codeFormValidation from './includes/codeFormValidation.js';
import homePage from "./pages/home.js";
import Jquery from 'jquery'
window.$ = Jquery;


accordion();
fixHeight();
mobileNav();
scrollToId();
modal();
loadMore();
select();
tariffsSlider();
feedbackFormValidation();
reviewsSlider();
registrationFormValidation();
phoneMask();
forgotFormValidation();
loginFormValidation();
passwordFormValidation();
codeFormValidation();
homePage();
newAccordion();
sidebar();
isDropdown();
closeAlert();
profileFormValidation();
searchFormValidation();
bookmarkFormValidation();
fileFormValidation();
createFormValidation();
modalSearchFormValidation();
